# Generated by Django 4.2.2 on 2023-11-14 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastralNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16)),
                ('long', models.CharField(max_length=9)),
                ('alt', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(blank=True, choices=[('query', 'Query'), ('result', 'Result query'), ('history', 'History query')], max_length=7)),
                ('response', models.BooleanField(blank=True)),
                ('timestamp', models.DateTimeField(blank=True)),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cadastralnumber')),
            ],
        ),
    ]
